spring:
  application:
    name: appointment-agent
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-flash-latest

google:
  credentials-path: ${GOOGLE_CREDENTIALS_PATH}

email:
  from: ${EMAIL_USERNAME}
  from-name: BrightCare Clinic
