spring:
  application:
    name: appointment-agent

server:
  port: 8080

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

gemini:
  api-key: ${GEMINI_API_KEY}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  credentials-path: ${GOOGLE_CREDENTIALS_PATH}

email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
